'use client';
import { useState } from 'react';
import { membersAPI } from '@/lib/api';
import { useRouter } from 'next/navigation';

/**
 * Register Member Page
 * 
 * Form page to register a new library member.
 * 
 * Features:
 * - Simple registration form
 * - Email validation
 * - Success/error feedback
 * - Auto-generated membership ID by backend
 * 
 * Form Fields:
 * - Name (required)
 * - Email (required, unique)
 * - Phone (required)
 * 
 * Auto-Generated by Backend:
 * - membershipId (e.g., MEM-ABC12345)
 * - registrationDate (today)
 * - status (ACTIVE)
 * 
 * Links To:
 * - membersAPI.register() - POST request to backend
 * - Backend generates membershipId and saves member
 */
export default function RegisterMember() {
  const router = useRouter();
  
  // Form state
  const [form, setForm] = useState({
    name: '',
    email: '',
    phone: ''
  });

  const [submitting, setSubmitting] = useState(false);

  // Handle form submission
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSubmitting(true);

    try {
      const response = await membersAPI.register(form);
      alert(`Member registered successfully!\nMembership ID: ${response.data.membershipId}`);
      router.push('/members'); // Redirect to members page
    } catch (err: any) {
      console.error('Error registering member:', err);
      alert(err.response?.data?.message || 'Error registering member. Email might already exist.');
      setSubmitting(false);
    }
  };

  return (
    <div className="max-w-2xl mx-auto p-8">
      <h1 className="text-3xl font-bold mb-8">Register New Member</h1>
      
      <form onSubmit={handleSubmit} className="bg-white p-8 rounded-lg shadow-lg space-y-6">
        {/* Full Name */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Full Name *
          </label>
          <input
            type="text"
            placeholder="Enter full name"
            required
            className="w-full p-4 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
            value={form.name}
            onChange={e => setForm({...form, name: e.target.value})}
          />
        </div>

        {/* Email Address */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Email Address *
          </label>
          <input
            type="email"
            placeholder="member@example.com"
            required
            className="w-full p-4 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
            value={form.email}
            onChange={e => setForm({...form, email: e.target.value})}
          />
          <p className="text-xs text-gray-500 mt-1">
            Must be unique - used for member identification
          </p>
        </div>

        {/* Phone Number */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Phone Number *
          </label>
          <input
            type="tel"
            placeholder="1234567890"
            required
            className="w-full p-4 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent"
            value={form.phone}
            onChange={e => setForm({...form, phone: e.target.value})}
          />
        </div>

        {/* Info Box */}
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
          <p className="text-sm text-blue-800">
            <strong>Note:</strong> A unique membership ID will be automatically generated upon registration.
          </p>
        </div>

        {/* Action Buttons */}
        <div className="flex gap-4 pt-4">
          <button
            type="submit"
            disabled={submitting}
            className="bg-green-600 text-white px-8 py-4 rounded-lg hover:bg-green-700 text-lg font-semibold transition disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {submitting ? 'Registering...' : 'Register Member'}
          </button>
          <button
            type="button"
            onClick={() => router.back()}
            className="bg-gray-500 text-white px-8 py-4 rounded-lg hover:bg-gray-600 transition"
          >
            Cancel
          </button>
        </div>
      </form>
    </div>
  );
}
